config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sites#index"

  get "about", to: "sites#about"
  get "index2", to: "sites#index2"
  get "mc_signup", to: "sites#mc_signup"

  get "individual", to: "sites#individual"

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :experiments  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/_footer.html.erb
<div class="before-footer">
</div>

<footer class="navbar-xs navbar-default navbar-fixed-bottom footer" role="navigation">
  <div class="container-fluid">
    <%= link_to "Home", root_path %> ·
    <a href="#">About</a> ·
    <%= link_to "Newsletter", mc_signup_path %> ·
    <a href="mailto:mike@crowdvitality.com">Contact</a>  
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" id="logo" class="navbar-brand">
        FarmReel
        <!-- <#%= image_tag "logo2.png", height: "220%" %> -->
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Individual Plans", individual_path %></li>
        <li><a href="mailto:mbetts7@gmail.com?subject=I'm interested in your Corporate wellness program!">Corporate Wellness</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <!-- <button type="button" class="btn btn-default"> -->
            <% if !user_signed_in? %>
              <%= link_to "Sign Up", new_user_registration_path %>
            <% end %>
          <!-- </button> -->
        </li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Stuff <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">My Lab</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Connected Devices</a></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Well Sumo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <!-- googlefonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans|Anton|Allan|Ropa+Sans|Exo+2|Pacifico|Lato:400,700' rel='stylesheet' type='text/css'>
  
  <!-- segment.com -->
  <script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
  analytics.load("2e66gmonzOMSGJDFP2ZEXE0oXtEX7DN5");
  analytics.page()
  }}();
  </script>
  
  <!-- mailchimp -->
  <script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us10.list-manage.com","uuid":"7ca0ed780e9911d0d6792db6b","lid":"c8573b8a86"}) })
  </script>

  <!-- optimizely -->
  <script src="//cdn.optimizely.com/js/2432320121.js"></script>
  
  <%= csrf_meta_tags %>
</head>
  <body>
<!--     <p class="notice"><#%= notice %></p>
    <p class="alert"><#%= alert %></p> -->
    <%= yield %>
  </body>
</html>

app/views/sites/about.html.erb
<%= render 'layouts/nav' %>
  
<div class="container before-footer">
  <div class="col-md-6 col-md-offset-3 site-section">
    <br>
    <p class="lead">- MISSION -</p> 
    <p>To bring together people with common health problems and performance goals. We believe groups of people can provide more powerful medicine than even the best doctor or coach.</p>
  </div>

  <div class="col-md-6 col-md-offset-3 site-section">
    <p class="lead">- HOW IT WORKS -</p> 
    <p> Through the power of knowledge sharing, experimentation and rich data, we can all achieve vitality.</p>
    <p> Join an experiment. Create an experiment. Join Groups. Share knowledge, track progress, see collective group data and results.</p>
  </div>

<!--   <div class="hidden-xs hidden-sm col-md-6 quote">
    <p>"All life is an experiment. The more experiments the better!"<cite title="Source Title"> - Ralph Waldo Emerson</cite></p>
  </div> -->
</div>

<%= render 'layouts/footer' %>

app/views/sites/index.html.erb
<%= render 'layouts/nav' %>

<!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
<header class="business-header">
    <div class="container tagline">
        <div class="row">
            <div class="col-lg-12">
                <h1>Wellness Made Simple</h1>
                <p>A Membership to Work Healthy From Anywhere</p>
                <p>The Wellness Membership that travels with you no matter where you work.</p>
                <!-- <h3>THE TOOLS TO LIVE HEALTHY AND OPTIMALLY</h3> -->
            </div>
        </div>
    </div>
</header>

<div class="container main">

    <div class="row">
      <div class="col-sm-4">
          <%= image_tag 'activity_trackers-cropped.png', class: 'img-circle img-responsive img-center hvr-grow', alt:'' %>
          <h2>Discounts</h2>
          <p>Member-only discounts on non-covered health expenses.</p>
      </div>
      <div class="col-sm-4">
          <img class="img-circle img-responsive img-center hvr-grow" src="http://placehold.it/300x300" alt="">
          <h2>Community</h2>
          <p>Join a community of folks that all want to improve their health</p>
      </div>
      <div class="col-sm-4">
          <img class="img-circle img-responsive img-center hvr-grow" src="http://placehold.it/300x300" alt="">
          <h2>Health Information</h2>
          <p>The latest in health information. Check out our blog and subscribe to updates <u>here</u></p>
      </div>
  </div>

</div>
<!-- end main container -->


<%= render 'layouts/footer' %>

app/views/sites/index2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ITS BETA - Landing Page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
   <div class="container">
    	<div class="row">        
			<header id="logo">
                <div class="col-md-12 col-sm-12">
                    
                    <a href="#" title="its beta">more&nbsp&nbsp&nbsp&nbsp<br>try ^ things</a>
                </div><!--/12-->
			</header>

            <section id="marketing-text">
                <div class="col-md-12 col-sm-12">
                	<h1>Stay tuned, we are launching very soon...</h1>
                    <p>ITS BETA is working hard to launch a new site that's going to revolutionize the way you do business. Leave us your email below, and we'll notify you the minute we open the doors.</p>
                </div><!--12-->
            </section><!--/marketing-text-->  

            <section id="subscribe" class="clearfix">
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                     <div class="row">
                        <form role="form" action="http://doozypixels.createsend.com/t/d/s/xky/" method="post">
                            <div class="col-md-7 col-sm-7"><input type="email" id="fieldEmail" name="cm-xky-xky" class="form-control input-lg" placeholder="Email Address" required /></div><!--7-->
                            <div class="col-md-5 col-sm-5 "><button class="btn btn-block btn-lg btn-theme">Subscribe</button></div><!--5-->
                        </form>
                    </div><!--row-->
                </div><!--/6-->
            </section><!--subscribe-->  
            
            <section id="features">
                <div class="col-md-3 col-sm-3">
                    <div class="feature-box">
                        <i class="fa fa-flag"></i>                            
                        <h2>Responsive Theme</h2>
                        <p>Talk about one of the biggest features that your new website is going to have.</p>
                    </div><!--feature-box-->
                </div><!--/3-->
                
                <div class="col-md-3 col-sm-3">
                    <div class="feature-box">
                        <i class="fa fa-flag"></i>                            
                        <h2>Font Awesome Icons</h2>
                        <p>Talk about one of the biggest features that your new website is going to have.</p>
                    </div><!--feature-box-->
                </div><!--/3-->
                
                <div class="col-md-3 col-sm-3">
                    <div class="feature-box">
                        <i class="hicon fa fa-envelope"></i>                            
                        <h2>Subscribe Signup Forms</h2>
                        <p>Theme supports two different email signup forms Mail Chimp &amp; Campaign Monitor</p>
                    </div><!--feature-box-->
                </div><!--/3-->
                
                <div class="col-md-3 col-sm-3">
                    <div class="feature-box">
                        <i class="fa fa-font"></i>                            
                        <h2>Google Web Fonts</h2>
                        <p>Talk about one of the biggest features that your new website is going to have.</p>
                    </div><!--feature-box-->
                </div><!--/3-->
            </section><!--features-->

			<footer>            
                <div class="col-md-12 col-sm-12">
                	<p class="social-text">
                        <span></span>
                        <i>For more details leading up to our launch <br/>check our below profiles</i>
                    </p>
                    <div class="social-icons">
                        <a href="#"><i class="fa fa-inbox"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-angellist"></i></a>
                    </div>
                    <small><i>&copy;2015 Well Sumo. All rights reserved.</i></small>
                </div><!--/12-->
            </footer>
        
        </div><!--/row-->
    </div><!--/container-->
  </body>
</html>

app/views/sites/mc_signup.html.erb
<div class="container">
  <!-- Begin MailChimp Signup Form -->
  <link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
  <style type="text/css">
    #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
    /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
       We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
  </style>
  <div id="mc_embed_signup">
  <form action="//crowdvitality.us10.list-manage.com/subscribe/post?u=7ca0ed780e9911d0d6792db6b&amp;id=c8573b8a86" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
      <div id="mc_embed_signup_scroll">
    <h2>Subscribe to our mailing list</h2>
  <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
  <div class="mc-field-group">
    <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
  </label>
    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
  </div>
  <div class="mc-field-group">
    <label for="mce-FNAME">First Name </label>
    <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
  </div>
  <div class="mc-field-group">
    <label for="mce-MMERGE3">What is your primary health or performance goal? </label>
    <input type="text" value="" name="MMERGE3" class="" id="mce-MMERGE3">
  </div>
    <div id="mce-responses" class="clear">
      <div class="response" id="mce-error-response" style="display:none"></div>
      <div class="response" id="mce-success-response" style="display:none"></div>
    </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
      <div style="position: absolute; left: -5000px;"><input type="text" name="b_7ca0ed780e9911d0d6792db6b_c8573b8a86" tabindex="-1" value=""></div>
      <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
      </div>
  </form>
  </div>
  <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[3]='MMERGE3';ftypes[3]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
  <!--End mc_embed_signup-->
</div>